"""add2 cascade in video

Revision ID: b55e42d96056
Revises: d5ebb211a78d
Create Date: 2023-05-16 12:12:06.683961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b55e42d96056'
down_revision = 'd5ebb211a78d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
