"""add column count_like in Video

Revision ID: ca2d89b2bebc
Revises: 094e509ee391
Create Date: 2023-05-08 17:21:40.283303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca2d89b2bebc'
down_revision = '094e509ee391'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('count_like', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video', 'count_like')
    # ### end Alembic commands ###
