"""add cascade in video

Revision ID: d5ebb211a78d
Revises: e9f51b8fedde
Create Date: 2023-05-16 11:51:47.476824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5ebb211a78d'
down_revision = 'e9f51b8fedde'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
