"""add column username in video

Revision ID: e9f51b8fedde
Revises: ca2d89b2bebc
Create Date: 2023-05-15 18:49:03.460176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9f51b8fedde'
down_revision = 'ca2d89b2bebc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('username', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video', 'username')
    # ### end Alembic commands ###
